# Generated by Django 4.1.7 on 2023-04-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='descriptions',
            new_name='description',
        ),
    ]
