# Generated by Django 4.1.7 on 2023-04-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_categorys_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='price', to='auctions.bid'),
            preserve_default=False,
        ),
    ]
