# Generated by Django 4.1.7 on 2023-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_lister_alter_auction_watcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-new_bid']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True, default='https://i.imgur.com/vLDtrNC.jpg'),
        ),
    ]
