# Generated by Django 4.1.7 on 2023-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
