# Generated by Django 4.1.2 on 2023-04-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_user_watchlist_alter_bid_listing_alter_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watcher',
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidder', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watcher', to='auctions.auction'),
        ),
    ]
