# Generated by Django 4.1.2 on 2023-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_auction_watcher_user_bids_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['listing']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['listing']},
        ),
    ]
